cluster:
  name: in-cluster
  namespace: argocd
  url: ""
  rancher:
    id: c-XXXX

openstack:
  project: ""
  auth_url: "https://openstack.example.com:5000"
  credential_id: ""
  credential_secret: ""

notifications: {}
#  notifications.argoproj.io/subscribe.slack: my-channel

sync: false

metallb:
  enabled: false
  version: "0.13.*"
  addresses: []

certmanager:
  enabled: false
  version: "1.*"
  email: acme@exmaple.com
  class: ""
  
ingresscontroller:
  enabled: false
  class: traefik
  publicIP: 1.1.1.1
  #privateIP: 1.1.1.2
  nginx:
    version: "4.*"
  traefik:
    version: "*"
    storageClass: ""
    #acme:
    #  email: acme@exmaple.com
    ports: {}
      # postgres:
      #   port: 5432
      #   expose: true
      #   exposedPort: 5432
      #   protocol: TCP

sealedsecrets:
  enabled: false
  version: "2.*"

# ----------------------------------------------------------------------
# MONITORING
# ----------------------------------------------------------------------

monitoring:
  enabled: false
  version: "102.*"

# ----------------------------------------------------------------------
# STORAGE
# ----------------------------------------------------------------------

nfs:
  enabled: false
  version: "4.*"
  servers:
    # special:
    #   server: server1
    #   path: /export/
    #   pathPattern:

longhorn:
  enabled: false
  version: "1.*"
  replicas: 3

cinder:
  enabled: false
  version: "2.*"

# ----------------------------------------------------------------------
# MISC RESOURCES
# ----------------------------------------------------------------------

raw:
  enabled: false
  version: "1.*"
  resources: []
  templates: []
